spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: always


mysql:
  url:
    local: "jdbc:mysql://localhost:3306/mdmx?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  username:
    local: "root"
  password:
    local: "88888888"

jpa:
  show_sql:
    local: true
  format_sql:
    local: true
  show_param:
    local: trace
  ddl-auto:
    local: none # create create-drop update validate none
