spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url.local}
    username: ${mysql.username.local}
    password: ${mysql.password.local}
  jpa:
    properties:
      hibernate:
        show_sql: ${jpa.show_sql.local}
    hibernate:
      ddl-auto: ${jpa.ddl-auto.local}


